### ISSUE TITLE
报错缺失文件moreserver

### ISSUE THREAD

**Issue by hellohappy0** [paulhybryant/docker-naotu#1]
![1549571701 1](https://user-images.githubusercontent.com/45357888/52441219-0fe20600-2b5b-11e9-902a-873b85f99e0a.png)
缺失的文件对应的网站打不开，也没找他类似的内容，请问你知道哪里可以找到吗？

**Comment by paulhybryant** [comment]
直接去掉这个js文件？或者忽略这个错误。影响使用么？
